### ISSUE TITLE
Unit doesn't compile

### ISSUE THREAD

**Issue by c-michail** [TheLazyTomcat/lib.InterlockedOps#1]
Hello,
  I get operand size mismatch on various functions. (Delphi)
  
Function InterlockedBitTest8(I: Pointer; Bit: Integer): Boolean;
...
{$ELSE}// -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -

          XOR   CL, CL
    LOCK  XADD  byte ptr [EAX], CL

          AND   Bit, 7
          BT    CX, Bit //<<<---HERE

          SETC  AL

{$ENDIF}
end;

**Comment by TheLazyTomcat** [comment]
Which compiler is it exactly (version number, target platform, architecture)?

EDIT
But you seem to be correct, "Bit" is declared as integer, therefore 32bit, but the operand size here is 16bit - I will look into it.

**Comment by c-michail** [comment]
Any news on that ? I want to compare it against TMonitor

Thank you

**Comment by TheLazyTomcat** [comment]
I am doing large-scale check and rewrite of all my public libraries because of bug in current FPC's assembler (yes, the fault is there, not here). InterlockedOps is next in line.
But considering that I am offline most of the time, I cannot say when the update will appear here.

BTW, isn't TMonitor a complete synchronization primitive? This unit is just providing interlocked calls, there is no synchronization object implemented here.

**Comment by TheLazyTomcat** [comment]
New version is uploaded. I have not targeted this specific error, but it should be corrected (I cannot test it in Delphi newer than 10.1, so can't say how it is, please let me know).

**Comment by c-michail** [comment]
Thank you i'll give it a try on my free time and report back!

**Comment by c-michail** [comment]
Your FastLocks is using this unit. 
With the last update I get 1 error on 32 bit and 1 on 64 bit. If i comment it compiles fine.

On 32 bit :
Function InterlockedBitTest32(I: Pointer; Bit: Integer): Boolean;
..
{$ELSE}// -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -

          XOR   ECX, ECX
    LOCK  XADD  dword ptr [EAX], ECX

          BT    ECX, DX // <-- Here

          SETC  AL

{$ENDIF}
end;

and on 64 bit:

Function InterlockedCompareExchange64(Destination: Pointer; Exchange,Comparand: UInt64): UInt64;
asm
{$IFDEF x64}
  {$IFDEF Windows}

          MOV   RAX, R8

    LOCK  CMPXCHG qword ptr [RCX], EDX <-- Here

Thank you

**Comment by TheLazyTomcat** [comment]
First I have to apologize for not responding this long - the thing is, I do not have access to any internet connection most of the time, that is why. If my status here is "Offline", then I am offline for real, and for long.
To the point - you are correct, these are another argument-size-mismatch errors. Will correct them asap.
Interesting that other compilers do not catch these...

EDIT
Should be corrected by now.
